### ISSUE TITLE
Fails to compile from source.

### ISSUE THREAD

**Issue by hendrikboom3** [UnicodingUnicorn/mangadex-downloader-2#1]
I git-cloned https://github.com/UnicodingUnicorn/mangadex-downloader-2.git
I updated rust using rustup
I cd'd to the mangadex-downloader-2 directory
Then issued 
     cargo run
It proceeded merrily for quite a while, reminding me of the installation procedure for OCaml modules, producing lots of ordinary-looking compilation progress messages, and then faile with:
   Compiling hyper v0.14.18
   Compiling hyper-tls v0.5.0
   Compiling reqwest v0.11.10
   Compiling mangadex-downloader v0.1.0 (/home/hendrik/dv/mangadex-dl/mangadex-downloader-2)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/main.rs:1:12
  |
1 | #![feature(iter_intersperse)]
  |            ^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `mangadex-downloader` due to previous error
hendrik@midwinter:~/dv/mangadex-dl/mangadex-downloader-2$ 

Rust's explanation for R0554 is:

Feature attributes are only allowed on the nightly release channel. Stable or
beta compilers will not comply.

Erroneous code example:

```
#![feature(lang_items)] // error: `#![feature]` may not be used on the
                        //        stable release channel
```

If you need the feature, make sure to use a nightly release of the compiler
(but be warned that the feature may be removed or altered in the future).

I have presumably compiled with the current stable release.  Is this your intention?
Or should I try to figure out how to get a nightly release version of rust?

-- hendrik
hendrik@topoi.pooq.com

**Comment by UnicodingUnicorn** [comment]
Ah, my bad. I forgot I have been running the nightly version of Rust all this while. Rust nightly is fairly straightforward to get with `rustup default nightly`.

**Comment by hendrikboom3** [comment]
Yes.  It compiles cleanly with nightly.  The messages now end with
```
   Compiling hyper-tls v0.5.0
   Compiling reqwest v0.11.10
   Compiling mangadex-downloader v0.1.0 (/home/hendrik/dv/mangadex-dl/mangadex-downloader-2)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 01s
     Running `target/debug/mangadex-downloader`
12:35:21 [ERROR] Manga url has not been specified
hendrik@midwinter:~/dv/mangadex-dl/mangadex-downloader-2$
```
This looks OK, given I haven't provided a URL.
There seem to be no other issues.  Does this mean I'm the first outside user?

-- hendrik

**Comment by UnicodingUnicorn** [comment]
Wonderful! Also, I guess you are! To be honest, I wasn't expecting anyone was going to use this.
